apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-credentials
  namespace: keycloak
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: rawhideron
  adminPassword: Zootopia1137
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak
type: Opaque
stringData:
  dbUser: rgoodman
  dbPassword: Zootopia1137
  dbName: keycloak
