apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-credentials
  namespace: keycloak
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: admin
  adminPassword: admin123
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak
type: Opaque
stringData:
  dbUser: keycloak
  dbPassword: keycloakpass
  dbName: keycloak
